### ISSUE TITLE
[1.20.1] Incorrect Forge tag

### ISSUE THREAD

**Issue by moon-st0ne** [mortuusars/Salt#11]
Salt should have the following tags for mod compatibility:
![image](https://github.com/mortuusars/Salt/assets/29065768/9965a22a-b494-42c7-b5f2-39ed7a8282f8)

However, it instead only has `forge:salts`, which is incorrect. No other mod uses `forge:salts`. Even if the other two are not used, the extra 's' should be removed from the tag.
![image](https://github.com/mortuusars/Salt/assets/29065768/dce7dbb3-d388-41fa-8dc0-84f701a4bc6b)

**Comment by mortuusars** [comment]
Added all tags to Salt in 1.2.3 version.
`forge:salts` is still used in recipes to not break existing modpacks and such.
