### ISSUE TITLE
Breaking Texture (1.19.2)

### ISSUE THREAD

**Issue by zachsai** [mortuusars/Salt#2]
Can you make it so the breaking texture follows the hitbox and is not in midair:
![image](https://github.com/mortuusars/Salt/assets/63996164/64081b0c-0190-4bae-badb-efcdc925cab7)

**Comment by mortuusars** [comment]
Here's how Mojang's Small Amethyst Bud breaks: 
![image](https://github.com/mortuusars/Salt/assets/65141267/e4819b94-aeb7-49ce-982e-7cc442173875)

So I don't think this can be fixed easily.
If you have a solution to this that does not require too much effort - please let me know.
