### ISSUE TITLE
Compatibility with Spoiled (forge 1.20.1)

### ISSUE THREAD

**Issue by katubug** [mortuusars/Salt#21]
Hi! I'm a small-time modpack maker who is hoping to use your mod in my pack, and I was wondering if you would consider adding compatibility with the Spoiled mod?

What I want is to have Salted foods not spoil (or spoil more slowly). But since your salt system is defined via NBT, and Spoiled's spoilage system is defined via tag, I don't see a way that I can make compatibility via KubeJS. I would be more than happy to donate a couple of bucks to both of y'all if this change could be possible!

Thanks so much for your time!

**Comment by mortuusars** [comment]
Closing as it's now implemented in Spoiled.

**Comment by katubug** [comment]
Thank you so much!
