### ISSUE TITLE
[Suggestion] Compat to MrCrayfishFurnitureMod-Refurbished mod

### ISSUE THREAD

**Issue by donmor** [mortuusars/Salt#22]
There's also salt item in that mod, crafted by evaporating water in their stoves, used to make foods. The two salt items can be made one since they're simply ingredients without special function.

Related issue: MrCrayfish/MrCrayfishFurnitureMod-Refurbished#64

**Comment by mortuusars** [comment]
Items from different mods cannot be merged into one. It's either one or the other, and in this case you'd need to have a dependency on other mod for yours to work. 

Salt's Salt item has `forge:salts` tag, and Salt's recipes expect this tag and not a specific item. If Furniture mod Salt has this tag you can use it in my recipes as well, and if their recipes use `forge:salts` tag you can use my salt in their recipes.

Expected way to fix duplicate items is to keep only one item in `forge:salts` tag (if it has two or more and you want to make it use single item) and hide unwanted items with KubeJS or something. It's up to the pack maker to choose items from what mods to keep.
