### ISSUE TITLE
Quark Tooltip food 1.19.2

### ISSUE THREAD

**Issue by zachsai** [mortuusars/Salt#4]
I also saw that quark adds a food tooltip similar to appleskin but with their own look.

I am unsure if support is native, but if it isnt, would be cool to add it for Quark Food Tooltip with salted tag :)

**Comment by mortuusars** [comment]
Quark does not allow modifying the food info as the AppleSkin does. They use only default food values, which depend only on item type.
I could change the Quark's code for salted foods with a mixin, but it's hacky and would break if Quark changes something.
