### ISSUE TITLE
Crash with Peculiars.

### ISSUE THREAD

**Issue by NotAPotter** [mortuusars/Salt#5]
When the Peculiars mod is present, going into creative inventory and mousing over a salt item crashes the game.

**Comment by mortuusars** [comment]
Please provide a crash log.

**Comment by NotAPotter** [comment]
[crash-2023-05-29_18.21.06-client.txt](https://github.com/mortuusars/Salt/files/11619008/crash-2023-05-29_18.21.06-client.txt)

**Comment by mortuusars** [comment]
I cannot reproduce it. 
From the log, error does not seem to be related to Salt at all. Peculiars mixin cannot find the Atmospheric class for some reason. It is especially strange because you don't even have atmospheric installed.
