### ISSUE TITLE
【Function】salted to slow down rotting

### ISSUE THREAD

**Issue by SeanChengN** [mortuusars/Salt#6]
In addition to taste and nutritional content, salting food can be stored longer, can it increase the food decay mechanism? This will give players more incentive to pickle food.

**Comment by mortuusars** [comment]
"Spoiled" mod is probably close to what you suggesting. But it has some issues with salted foods. To not repeat myself here, you can read the comment that I wrote in response to other user on the issue. It's on salt curseforge page, 3rd comment or so.

**Comment by SeanChengN** [comment]
> "Spoiled" mod is probably close to what you suggesting. But it has some issues with salted foods. To not repeat myself here, you can read the comment that I wrote in response to other user on the issue. It's on salt curseforge page, 3rd comment or so.

oh! get it.
